### ISSUE TITLE
Assertion Error transfering geojson annotations

### ISSUE THREAD

**Issue by marcosgly** [MathOnco/valis#173]
Hi! This looks incredible! I'm currently trying to run an example to transfer annotations in the form of geojson files but I'm getting the error below. I think this looks similar to #12 and #33 but I thought I'd check again as there have been some updates to some of these packages.
I'm running this with numba 0.60.0 ; interpolation 2.2.6 ; valis 1.0.0rc12. I guess I could work with an earlier version of python (<3.11) and install the versions with which it worked when #33 was live but I just wanted to check if there was maybe a different way before I do that? 
Any help would be much appreciated, thank you very much!
`
# Perform registration
registrar = registration.Valis(slide_src_dir, results_dst_dir)
rigid_registrar, non_rigid_registrar, error_df = registrar.register()

# Transfer annotation from image associated with annotation_img_f and image associated with target_img_f
annotation_source_slide = registrar.get_slide(annotation_img_f)
target_slide = registrar.get_slide(target_img_f)

warped_geojson_from_to = annotation_source_slide.warp_geojson_from_to(annotation_geojson_f, target_slide)
warped_geojson = annotation_source_slide.warp_geojson(annotation_geojson_f)

# Save annotation as warped_geojson_annotation_f, which can be dragged and dropped into QuPath
with open(warped_geojson_annotation_f, 'w') as f:
    json.dump(warped_geojson, f)`

'
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
JVM has been initialized. Be sure to call registration.kill_jvm() or slide_io.kill_jvm() at the end of your script.

==== Converting images

100%|██████████| 4/4 [00:04<00:00,  1.05s/it]

==== Processing images

100%|██████████| 4/4 [00:02<00:00,  1.47it/s]

==== Normalizing images

100%|██████████| 4/4 [00:00<00:00,  4.47it/s]

==== Rigid registraration

100%|██████████| 4/4 [00:00<00:00,  4.57it/s]

======== Detecting features

100%|██████████| 4/4 [00:00<00:00, 22.21it/s]

======== Matching images

100%|██████████| 6/6 [00:00<00:00, 15.06it/s]

======== Sorting images

======== Calculating transformations

100%|██████████| 3/3 [00:00<00:00, 2998.79it/s]
100%|██████████| 4/4 [00:00<00:00, 4002.20it/s]

======== Rigid registration complete in 0.999 seconds

==== Non-rigid registraration

======== Preparing images for non-rigid registraration

100%|██████████| 4/4 [00:13<00:00,  3.30s/it]
100%|██████████| 3/3 [00:12<00:00,  4.21s/it]

======== Non-rigid registration complete in 13.584 seconds

Traceback (most recent call last):
  File "C:\Users\hfx993\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\valis\registration.py", line 3380, in register
    non_rigid_registrar = self.non_rigid_register(rigid_registrar,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hfx993\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\valis\registration.py", line 3031, in non_rigid_register
    thumbanil_deform_grid = viz.color_displacement_tri_grid(bk_dx=thumbnail_bk_dxdy[..., 0],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hfx993\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\valis\viz.py", line 781, in color_displacement_tri_grid
    warped_xy = warp_tools.warp_xy(tri_verts, bk_dxdy=[padded_dx, padded_dy])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hfx993\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\valis\warp_tools.py", line 2176, in warp_xy
    warped_xy = _warp_xy_numpy(xy, M, transformation_src_shape_rc=transformation_src_shape_rc,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hfx993\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\valis\warp_tools.py", line 2096, in _warp_xy_numpy
    grid = UCGrid((0.0, float(displacement_shape_rc[1]-1), displacement_shape_rc[1]),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hfx993\AppData\Roaming\Python\Python311\site-packages\interpolation\splines\__init__.py", line 15, in UCGrid
    assert numba.typeof(a) == tt
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError

JVM has been killed. If this was due to an error, then a new Python session will need to be started
C:\Users\hfx993\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\valis\valtils.py:75: UserWarning: 
  warnings.warn(warning_msg, warning_type)
Traceback (most recent call last):

  File ~\AppData\Local\anaconda3\envs\valis_env\Lib\site-packages\spyder_kernels\customize\utils.py:209 in exec_encapsulate_locals
    exec_fun(compile(code_ast, filename, "exec"), globals)

  File c:\users\hfx993\\documents\python scripts\alternative_path_addition.py:122
    warped_geojson_from_to = annotation_source_slide.warp_geojson_from_to(annotation_geojson_f, target_slide)

AttributeError: 'Slide' object has no attribute 'warp_geojson_from_to'

**Comment by cdgatenbee** [comment]
Hi @marcosgly, 

Unfortunately, `warp_geojson_from_to` was added in version 1.0.0rc13, and the`interpolation` and `numba` packages were removed as a dependencies in version 1.0.3, so you'll need to update your version of valis. It should work with Python 3.11 though, although if that's an issue, could you create a python 3.10 virtual environment? I would also usually suggest using the Docker container, but there are a few issues with it right now that I need to figure out. Anyhow, please try updating valis and let me know if the annotation transfer works for you. 

Best,
-Chandler

**Comment by marcosgly** [comment]
Hi Chandler, 

Thank you so much for the quick reply! It seems like the slide registration is working now but the warping of the annotation is taking quite long. I've let the command: annotation_source_slide.warp_geojson_from_to(annotation_geojson_f, target_slide) run for over an hour but the progress bar just shows Warping annotations: 0annotation [00:00, ?annotation/s]. Could there be a problem with the geojson being in physical units as opposed to pixel units or is this just how long it takes? Alternatively do you think there could be any other problem? 

Thank you, 
Marcos

**Comment by cdgatenbee** [comment]
Hi @marcosgly, 

Glad the slide alignments are looking good! I don't think that the annotation warping should take this long though. I don't know if it is the source of this issue, but valis does expect the annotations to be in pixel units, instead of physical units. But this makes me think that `warp_geojson_from_to` should have argument that would allow you to scale for physical units. I've been running tests/benchmarking on the latest version of valis, so maybe this is something I could squeeze in before pushing the update. But, in the meantime, could you try scaling the annotations to pixel units and see if this problem persists? 

Best,
-Chandler
